### ISSUE TITLE
자동생성된 app.service 관련 코드 삭제

### ISSUE THREAD

**Issue by lukasjhan** [tree-s-computer/login#10]

**Comment by yunseorim1116** [comment]
이것 해결되지 않았나요~?!

**Comment by lukasjhan** [comment]
@yunseorim1116 그때 저희 PR에서 다시 복구했었어요. 로그인 기능 구현이랑 상관없는 부분이어서 PR을 분리하기로 했었어요.

**Comment by yunseorim1116** [comment]
> @yunseorim1116 그때 저희 PR에서 다시 복구했었어요. 로그인 기능 구현이랑 상관없는 부분이어서 PR을 분리하기로 했었어요.

제가 착각했습니다 엉엉
pr올렸어요!

**Comment by lukasjhan** [comment]
> > @yunseorim1116 그때 저희 PR에서 다시 복구했었어요. 로그인 기능 구현이랑 상관없는 부분이어서 PR을 분리하기로 했었어요.
> 
> 제가 착각했습니다 �엉엉 pr올렸어요!

머지했습니다. 고생많으셨어요 :)
